# Generated by Django 4.0.3 on 2022-04-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
